### ISSUE TITLE
Workflow error when trying to add new user

### ISSUE THREAD

**Issue by bnm12** [burningice2866/CompositeC1Contrib.Security#1]
Hey,

Running on the official Composite C1
Build no. 5.0.6029.22524

I get this error when i try to add a new user via. the security module on the system page:
Interestingly it _does_ actually add the user

```
InvalidOperationException:
Error executing workflow fb2c6666-e9ba-4d75-9ccf-c636acf2b930
Stack trace:
   at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(Guid instanceId) in C:\tmp\SIMPortalen\Composite\C1Console\Workflow\WorkflowFacadeImpl.cs:line 279
   at Composite.C1Console.Workflow.WorkflowFacade.RunWorkflow(Guid instanceId) in C:\tmp\SIMPortalen\Composite\C1Console\Workflow\WorkflowFacade.cs:line 140
   at Composite.C1Console.Workflow.WorkflowFlowController.OnFinish(FlowToken flowToken, Dictionary`2 bindings, FlowControllerServicesContainer serviceContainer) in C:\tmp\SIMPortalen\Composite\C1Console\Workflow\WorkflowFlowController.cs:line 273
   at Composite.Core.WebClient.FlowMediators.FormFlowRendering.FormFlowUiDefinitionRenderer.BaseEventHandler(String consoleId, String elementProviderName, FlowToken flowToken, FormFlowUiDefinition formFlowUiCommand, FlowControllerServicesContainer servicesContainer, Dictionary`2 eventHandlers, IFormEventIdentifier localScopeEventIdentifier, Flo
ArgumentNullException:
Value cannot be null.
Parameter name: flowControllerServicesContainer
Stack trace:
   at Composite.Verify.ThrowArgumentNullException(String parameterName) in C:\tmp\SIMPortalen\Composite\Verify.cs:line 173
   at Composite.Verify.ArgumentNotNull(Object value, String paramName) in C:\tmp\SIMPortalen\Composite\Verify.cs:line 26
   at Composite.C1Console.Actions.AddNewTreeRefresher..ctor(EntityToken parentEntityToken, FlowControllerServicesContainer flowControllerServicesContainer) in C:\tmp\SIMPortalen\Composite\C1Console\Actions\AddNewTreeRefresher.cs:line 25
   at Composite.C1Console.Workflow.Activities.FormsWorkflow.CreateAddNewTreeRefresher(EntityToken parentEntityToken) in C:\tmp\SIMPortalen\Composite\C1Console\Workflow\Activities\FormsWorkflow.cs:line 649
   at CompositeC1Contrib.Security.C1Console.Workflows.AddUserWorkflow.OnFinish(Object sender, EventArgs e) in C:\tmp\SIMPortalen\C1.contrib.security\Security\C1Console\Workflows\AddUserWorkflow.cs:line 54
```

**Comment by burningice2866** [comment]
@bnm12 Thank you for reporting your issue. I see that you're running a custom build from source - can you help me a bit more out by breaking into the code.

Can we agree that the error originates from here https://github.com/burningice2866/CompositeC1Contrib.Security/blob/master/Security/C1Console/Workflows/AddUserWorkflow.cs#L54. To me it fails due to some internals to C1, but can you do me a favor and inspect the value of `EntityToken` on line 54.

I have to admit that i haven't done any extensive testing on version 5.0, but a quick look at the code doesn't reveal anything out of the ordinary which shouldn't work.

**Comment by bnm12** [comment]
The value is: 
{Type = "", Source = "", Id = "Users"}
http://puu.sh/pTkJl/3247d39fb7.png

**Comment by bnm12** [comment]
Now I'm getting this error:
Not exactly sure why it changed, and it still creates the user...

```
InvalidOperationException:
Error executing workflow 2123b046-12c2-4d4e-af56-6a408e8a70bf
Stack trace:
   at Composite.C1Console.Workflow.WorkflowFacadeImpl.RunWorkflow(Guid instanceId) in C:\tmp\SIMPortalen\Composite\C1Console\Workflow\WorkflowFacadeImpl.cs:line 279
   at Composite.C1Console.Workflow.WorkflowFacade.RunWorkflow(Guid instanceId) in C:\tmp\SIMPortalen\Composite\C1Console\Workflow\WorkflowFacade.cs:line 140
   at Composite.C1Console.Workflow.WorkflowFlowController.OnFinish(FlowToken flowToken, Dictionary`2 bindings, FlowControllerServicesContainer serviceContainer) in C:\tmp\SIMPortalen\Composite\C1Console\Workflow\WorkflowFlowController.cs:line 273
   at Composite.Core.WebClient.FlowMediators.FormFlowRendering.FormFlowUiDefinitionRenderer.BaseEventHandler(String consoleId, String elementProviderName, FlowToken flowToken, FormFlowUiDefinition formFlowUiCommand, FlowControllerServicesContainer servicesContainer, Dictionary`2 eventHandlers, IFormEventIdentifier localScopeEventIdentifier, Flo
ArgumentException:
The input workflow type must define a public, parameterless constructor.
Stack trace:
   at System.Workflow.Runtime.Hosting.DefaultWorkflowLoaderService.CreateInstance(Type workflowType)
   at System.Workflow.Runtime.WorkflowDefinitionDispenser.LoadRootActivity(Type workflowType, Boolean createDefinition, Boolean initForRuntime)
   at System.Workflow.Runtime.WorkflowDefinitionDispenser.MruCache.GetOrGenerateDefinition(Type type, String xomlText, String rulesText, Byte[] md5Codes, Boolean initForRuntime, Boolean& exist)
   at System.Workflow.Runtime.WorkflowDefinitionDispenser.GetRootActivity(Type workflowType, Boolean createNew, Boolean initForRuntime)
   at System.Workflow.Runtime.WorkflowRuntime.InitializeExecutor(Guid instanceId, CreationContext context, WorkflowExecutor executor, WorkflowInstance workflowInstance)
   at System.Workflow.Runtime.WorkflowRuntime.Load(Guid key, CreationContext context, WorkflowInstance workflowInstance)
   at System.Workflow.Runtime.WorkflowRuntime.GetWorkflowExecutor(Guid 
Generated 2016-07-07 14:12
An unfortunate error has occurred.
Details
```

**Comment by bnm12** [comment]
@burningice2866 Do you need more than that?

**Comment by burningice2866** [comment]
@bnm12 weird why the first error went away !?

The second error is because there is no parameterless constructor on this class https://github.com/burningice2866/CompositeC1Contrib.Security/blob/65aee8a019cc3e81a8bd94b229ede26f5c6a84b4/Security/C1Console/Workflows/EditUserWorkflow.cs. It's actually a bit embarrassing because i fixed that months ago but i see that i never pushed it.

Give me 2 minutes, and there will be an update with the fix.

**Comment by burningice2866** [comment]
@bnm12 there you go https://github.com/burningice2866/CompositeC1Contrib.Security/commit/57942aa0e8b34033db08827365f72130f6e3205f

That's what happens when you're the only one using the code. I'm glad more eyes are willing to look at it.

**Comment by bnm12** [comment]
@burningice2866 I'm also getting complaints about not having a parameterless constructor if I try editing users, so it might be a general issue with how workflows worked vs. how they work now?

**Comment by burningice2866** [comment]
@bnm12 What happens after an user is added is that the EditWorkFlow is invoked, that's why you get the exact same error when adding or editing a user

https://github.com/burningice2866/CompositeC1Contrib.Security/blob/master/Security/C1Console/Workflows/AddUserWorkflow.cs#L49

**Comment by bnm12** [comment]
@burningice2866 ah, well that makes sense then :)
I'm happy to report that I no longer get that issue.

Now that I can see the edit users page: What are roles, and how do I add/modify them?

**Comment by burningice2866** [comment]
@bnm12 If you plan to manage users and roles within the C1 Console, and not from an external system, you should install the Extranet package as well, which allows you to create roles and assign them to users.

https://github.com/burningice2866/CompositeC1Contrib.Security/tree/master/Security.Extranet

The reason for this composition is because the majority of sites i develop has an external system that defines permissions and roles and all they need the website to do is to hold the credentials (passwords) and define what roles can access what pages, media etc..

**Comment by bnm12** [comment]
@burningice2866 I have the extranet package installed, but I can't figure out where to create roles
http://puu.sh/pXMda/f5f775b5cb.png

**Comment by burningice2866** [comment]
@bnm12 something is missing in your installation then - the Extranet package adds a new perspective next to Content, Media, System etc.

https://github.com/burningice2866/CompositeC1Contrib.Security/blob/master/Security.Extranet/Package/config/App_Data/Composite/composite.config#L6

**Comment by bnm12** [comment]
@burningice2866 I have that in my config: http://puu.sh/pXMNR/67f2000253.png

**Comment by burningice2866** [comment]
@bnm12 but no Extranet perspective is showing up in your console?

Can you check the permissions for the user you're logged in with. Under the permissions-tab, if you have explicitly selected what perspectives you have access to, new perspectives will be un-selected.

**Comment by bnm12** [comment]
@burningice2866 I'm logged in as the default admin account, and I haven't touched the permissions...
Looking at it now I can't actually see anywhere where I can set permissions for specific modules, it's only: Administrate, publish, configure, read, add, edit, delete, approve

**Comment by burningice2866** [comment]
@bnm12 Its a setting on the user, not Permissions per se.

![image](https://cloud.githubusercontent.com/assets/333952/16729551/82096d24-476d-11e6-96a9-479cb05bd6a3.png)

**Comment by bnm12** [comment]
@burningice2866 got it! I see it now http://puu.sh/pXPhN/1b5d999b6b.png
Looks a bit wonkey though

**Comment by burningice2866** [comment]
@bnm12 this is because you didn't add the users as Extranet Users to start with, but only as basic [Membership Users](https://msdn.microsoft.com/en-us/library/system.web.security.membershipuser%28v=vs.110%29.aspx), which doesn't have the concept of name.

The extranet package adds the concept of Profiles which are metadata to a Membership User, and can contain whatever data you want - [default its Firstname, Lastname and Roles](https://github.com/burningice2866/CompositeC1Contrib.Security/blob/master/Security.Extranet/EditProfileHandler.cs). So if you go and edit those three users you can specify some names which will render in the tree, and Extranet Users you add from now on will contain a name since you'll be prompted for it when addding.

**Comment by burningice2866** [comment]
@bnm12 One could argue that the Extranet Elementprovider should fallback to show the [MembershipUser.UserName](https://msdn.microsoft.com/en-us/library/system.web.security.membershipuser.username%28v=vs.110%29.aspx) field if [Firstname and Lastname](https://github.com/burningice2866/CompositeC1Contrib.Security/blob/master/Security.Extranet/C1Console/ElementProviders/ExtranetElementProvider.cs#L50) is empty and i wouldn't reject such a Pull Request. It's not something that would normally be necessary since all Extranet Users created througt the Extranet perspective would have a Firstname and Lastname.

**Comment by bnm12** [comment]
@burningice2866 Ah Thanks, I see that now.

The roles are still a bit of a mystery to me, I've tried adding one, but I don't understand what I can use them for. They don't seem to show up when I'm setting permissions for pages in that dialog I only see "AUTHENTICATED" and "ANONYMOUS"

**Comment by burningice2866** [comment]
@bnm12 have you ensured that the [Extranet RoleProvider](https://github.com/burningice2866/CompositeC1Contrib.Security/blob/master/Security.Extranet/Web/ExtranetRoleProvider.cs) has been [added to web.config](https://github.com/burningice2866/CompositeC1Contrib.Security/blob/master/Security.Extranet/Package/config/web.config#L18), at that is has been set as the default one

**Comment by bnm12** [comment]
@burningice2866 it was added, but not set as default. My bad.

**Comment by burningice2866** [comment]
@bnm12 No worries! Its a lot of moving parts and i have failed at providing any form of basic documentation.

**Comment by bnm12** [comment]
@burningice2866 That is true, but I still feel a bit helpless being a developer myself I can usually work stuff like this out on my own, but I just don't have the required Composite domain knowledge to really grasp it all yet.

Right now I'm looking for a login form function, I don't know if you provide one with the extranet module, or at least have a reference implementation I can have a look at.

I've noticed that you can redirect to a login page, which seems to work beautifully, but then I kinda need a login page :P 
Also with the WYSIWYG editor in Composite 5 do you think it would be possible to bypass the login/redirect while the page is in edit mode?

(Also a signup and forgot password function/page would be nice)

**Comment by burningice2866** [comment]
@bnm12 There are no form's out of the box, but IMHO Login/Signup/ForgotPassword forms plays very nicely together with my https://github.com/burningice2866/CompositeC1Contrib.FormBuilder/tree/master/FormBuilder.POCO project with is a Code First approach to creating forms.

A simple login-form using FormBuilder.POCO would look like this

```
[FormName("Forms", "LoginForm")]
public class LoginForm : IPOCOForm
{
    [FieldLabel("Email")]
    [RequiredField("Email is required")]
    [CredentialsValidator("Wrong credentials", "Password")]
    public string Email { get; set; }

    [FieldLabel("Password")]
    [PasswordInputElement]
    [RequiredField("Password is required")]
    public string Password { get; set; }

    public void Submit()
    {
        var userName = Membership.GetUserNameByEmail(Email);
        var membershipUser = Membership.GetUser(userName);

        membershipUser.LastActivityDate = membershipUser.LastLoginDate = DateTime.UtcNow;

        Membership.UpdateUser(membershipUser);

        FormsAuthentication.SetAuthCookie(userName, false);

        var ctx = HttpContext.Current;

        ctx.Response.StatusCode = (int)HttpStatusCode.Redirect;
        ctx.Response.RedirectLocation = GetRedirectUrl();
    }

    private static string GetRedirectUrl()
    {
        var url = FormsAuthentication.GetRedirectUrl(String.Empty, false);
        if (url == null || url == FormsAuthentication.DefaultUrl)
        {
            return "/";
        }

        return url;
    }
}
```

And if you combine it with the [Email project](https://github.com/burningice2866/CompositeC1Contrib.Email) which lets you manage email template from within C1 Console, you can create a simple Forgot Password form like this

```
[FormName("Forms", "ForgotPasswordForm")]
public class ForgotPasswordForm : IPOCOForm
{
    [FieldLabel("Email")]
    [RequiredField("Email address is required.")]
    [EmailFieldValidator("Invalid email address")]
    public string Email { get; set; }

    public void Submit()
    {
        var user = Membership.FindUsersByEmail(Email).Cast<MembershipUser>().SingleOrDefault();
        if (user == null)
        {
            return;
        }

        var newPassword = user.ResetPassword();

        using (var data = new DataConnection())
        {
            var customer = data.Get<ICustomer>().Single(c => c.Id == user.UserName);

            var model = new ResetPasswordMailModel
            {
                Name = customer.Name,
                NewPassword = newPassword
            };

            using (var message = MailModelsFacade.BuildMailMessage(model))
            {
                message.To.Add(user.Email);

                MailsFacade.EnqueueMessage(message);
            }
        }
    }
}
```

**Comment by bnm12** [comment]
@burningice2866 Thanks, I'll give it a shot :)
